import sys

def winnow(windowSize, fileName):

    hashes = []
    with open(fileName, "r") as file:
        for line in file:
            hashes.append(int(line[0:len(line)-1])) # add the line without newline as an int

    windows = []
    fingerPrints = {} # fingerprints in format {index : hash}
    for i in range(0, len(hashes) - windowSize + 1):
        window = hashes[i : i + windowSize] # get the current window

        minHash = sys.maxsize
        minIndex = 0

        # getting rightmost minimum hash from the current window
        for j in range(len(window)):
            if window[j] <= minHash:
                minHash = window[j]
                minIndex = i + j # i + j is the absolute index
        
        if not minIndex in fingerPrints:
            fingerPrints[minIndex] = minHash    

    return fingerPrints

    # print(fingerPrints)
    # print("total fingerprints: " + str(len(fingerPrints)))

            

winnow(4, "fingerPrint.txt") # fingerPrint.txt was generated by hashFingerprint.py on the testing.txt file in this directory